# Generated by Django 5.2.8 on 2026-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plantype',
            field=models.CharField(choices=[('free', 'FREE'), ('paid', 'PAID'), ('professional', 'PROFESSIONAL')], default='free', max_length=50),
        ),
    ]
