# Generated by Django 5.2.8 on 2026-06-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=64, null=True),
        ),
    ]
