# Generated by Django 5.2.8 on 2026-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plantype',
            field=models.CharField(choices=[('free', 'FREE'), ('core', 'CORE'), ('builder', 'BUILDER'), ('anchor', 'ANCHOR')], default='free', max_length=50),
        ),
    ]
