# Generated by Django 5.2.8 on 2026-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadthumbnail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadthumbnail',
            name='active_count',
            field=models.IntegerField(default=0),
        ),
    ]
