# Generated by Django 5.2.8 on 2026-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_add_uploadthumbnail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadthumbnail',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
