# Generated by Django 5.2.8 on 2026-06-24 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBlockKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadPdfForAiKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_restriction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_voice_type',
            field=models.CharField(choices=[('professional', 'PROFESSIONAL'), ('friendly', 'FRIENDLY'), ('formal', 'FORMAL'), ('casual', 'CASUAL')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='avg_time_response',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='response_length',
            field=models.CharField(choices=[('short', 'SHORT'), ('medium', 'MEDIUM'), ('long', 'LONG')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='total_queary_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='total_spam_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='ai_response',
            field=models.TextField(blank=True, default='1', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_block_keyword',
            field=models.ManyToManyField(blank=True, to='chatsystem.aiblockkeyword'),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatsystem.uploadpdfforaiknowledge'),
        ),
    ]
