# Generated by Django 5.2.8 on 2026-06-24 05:23

import chatsystem.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0002_aiblockkeyword_uploadpdfforaiknowledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_restriction', models.TextField(blank=True, default='')),
                ('response_style', models.CharField(choices=chatsystem.enums.AI_VOICE_TYPE.choices, default='formal', max_length=50)),
                ('total_query_count', models.BigIntegerField(default=0)),
                ('today_query_count', models.IntegerField(default=0)),
                ('today_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='knowledge_pdfs/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('response_text', models.TextField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_block_keyword',
        ),
        migrations.RemoveField(
            model_name='message',
            name='pdf_knowledge',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_restriction',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_voice_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='avg_time_response',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response_length',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='total_queary_count',
        ),
        migrations.RemoveField(
            model_name='message',
            name='total_spam_count',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='AIBlockKeyWord',
        ),
        migrations.DeleteModel(
            name='UploadPdfForAiKnowledge',
        ),
    ]
