# Generated by Django 5.2.8 on 2026-06-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0003_aisetting_blockedkeyword_knowledgepdf_userquerylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatsystem.chatroom'),
        ),
    ]
