# Generated by Django 5.2.8 on 2026-06-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiation', '0002_notification_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='set_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
