# Generated by Django 5.2.8 on 2026-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifiation', '0003_alter_email_set_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user_time_zone',
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
    ]
