# Generated by Django 5.2.8 on 2026-06-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='questions_per_month',
            field=models.IntegerField(default=5, help_text='-1 for unlimited'),
        ),
        migrations.AddField(
            model_name='plans',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plantype',
            field=models.CharField(choices=[('free', 'FREE'), ('core', 'CORE'), ('builder', 'BUILDER'), ('anchor', 'ANCHOR')], default='free', max_length=50),
        ),
    ]
