# Generated by Django 5.2.8 on 2026-06-27 06:59

import plan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plans_badge_plans_billing_cycle_plans_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='features',
            field=models.JSONField(default=plan.models.Plans.default_features, help_text='List of features for this plan'),
        ),
    ]
